<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Http\Controllers\TotpController;
use App\Models\Edition;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PragmaRX\Google2FAQRCode\Google2FA;
use Tests\TestCase;
use Tests\Unit\TotpServiceTest;

/**
 * Enrolling an authenticator app, end to end.
 *
 * The codes here are generated by the real library from the real secret on the
 * account, so these tests exercise the same arithmetic a phone would. A test that
 * stubbed the verifier would prove the plumbing is wired up and nothing at all
 * about whether a valid code is accepted.
 *
 * @see TotpController
 * @see TotpServiceTest
 */
class TotpEnrolmentTest extends TestCase
{
    use RefreshDatabase;

    private const DIGITS = 6;

    protected function setUp(): void
    {
        parent::setUp();

        config([
            'totp.required' => true,
            'totp.issuer' => 'ARABCIA 2026',
            'totp.digits' => self::DIGITS,
            'totp.window' => 1,
            'totp.recovery_codes' => 8,
            'totp.secret_bytes' => 32,
        ]);
    }

    // --- The happy path ---------------------------------------------------

    public function test_the_setup_page_shows_a_qr_code_and_the_same_secret_to_type(): void
    {
        $user = $this->unconfirmedUser();

        $response = $this->actingAs($user)->get(route('totp.setup'));

        $response->assertOk();

        $secret = (string) $user->fresh()->totp_secret;

        $this->assertNotSame('', $secret, 'No secret was written to the account.');

        // Printed in groups of four, the way an authenticator app shows it, so
        // the typeable key is literally on the page alongside the QR.
        $response->assertSee(trim(chunk_split($secret, 4, ' ')));
        // The inline SVG data URL, not a link to an image endpoint: the URI
        // carries the shared secret, so it must not be a separately cacheable
        // request.
        $response->assertSee('data:image/svg+xml;base64', escape: false);
    }

    /**
     * The secret must survive a reload.
     *
     * Regenerating on every GET would invalidate the QR code a visitor is halfway
     * through scanning, and hand a refresh the power to quietly break an
     * enrolment in progress.
     */
    public function test_reloading_the_page_keeps_the_same_secret(): void
    {
        $user = $this->unconfirmedUser();

        $this->actingAs($user)->get(route('totp.setup'));
        $first = (string) $user->fresh()->totp_secret;

        $this->actingAs($user)->get(route('totp.setup'));
        $second = (string) $user->fresh()->totp_secret;

        $this->assertSame($first, $second);
    }

    public function test_a_valid_code_enrols_the_account(): void
    {
        $user = $this->unconfirmedUser();

        $this->actingAs($user)->get(route('totp.setup'));

        $response = $this->actingAs($user)->post(route('totp.confirm'), [
            'code' => $this->currentCodeFor($user),
        ]);

        $response->assertRedirect(route('totp.recovery-codes'));

        $user->refresh();

        $this->assertNotNull($user->totp_confirmed_at);
        $this->assertTrue($user->hasConfirmedTotp());
        $this->assertCount(8, $user->totp_recovery_codes);
    }

    // --- Refusals ---------------------------------------------------------

    /**
     * The load-bearing refusal: a secret the visitor never proved they stored.
     *
     * Writing a secret is not enrolment. If `begin()` alone marked an account as
     * enrolled, the gate would be walked through by loading one page.
     */
    public function test_merely_opening_the_setup_page_does_not_enrol_the_account(): void
    {
        $user = $this->unconfirmedUser();

        $this->actingAs($user)->get(route('totp.setup'))->assertOk();

        $user->refresh();

        $this->assertNotNull($user->totp_secret, 'The secret should have been written.');
        $this->assertNull($user->totp_confirmed_at, 'But the account must not be enrolled.');
        $this->assertFalse($user->hasConfirmedTotp());
        $this->assertFalse($user->canRegister());
    }

    public function test_a_wrong_code_does_not_enrol_the_account(): void
    {
        $user = $this->unconfirmedUser();

        $this->actingAs($user)->get(route('totp.setup'));

        $this->actingAs($user)
            ->post(route('totp.confirm'), ['code' => '000000'])
            ->assertSessionHasErrors('code');

        $this->assertNull($user->fresh()->totp_confirmed_at);
    }

    /**
     * A perfectly valid code — for somebody else's secret — must not enrol this
     * account. The only thing that makes a code meaningful is the secret it was
     * computed from.
     */
    public function test_a_code_from_a_different_secret_does_not_enrol_the_account(): void
    {
        $user = $this->unconfirmedUser();

        $this->actingAs($user)->get(route('totp.setup'));

        $engine = app(Google2FA::class);
        $foreignCode = $engine->getCurrentOtp($engine->generateSecretKey(32));

        $this->actingAs($user)
            ->post(route('totp.confirm'), ['code' => $foreignCode])
            ->assertSessionHasErrors('code');

        $this->assertNull($user->fresh()->totp_confirmed_at);
    }

    public function test_a_code_that_is_not_the_right_length_is_refused(): void
    {
        $user = $this->unconfirmedUser();

        $this->actingAs($user)->get(route('totp.setup'));

        $this->actingAs($user)
            ->post(route('totp.confirm'), ['code' => '123'])
            ->assertSessionHasErrors('code');

        $this->assertNull($user->fresh()->totp_confirmed_at);
    }

    public function test_a_guest_cannot_enrol(): void
    {
        $this->get(route('totp.setup'))->assertRedirect(route('login'));
        $this->post(route('totp.confirm'), ['code' => '123456'])->assertRedirect(route('login'));
    }

    /**
     * A confirmation timestamp with no secret behind it is not an enrolment.
     *
     * The two columns can disagree — a secret cleared while the date stayed, a
     * partial write, a column added to existing rows with a backfill. Checking
     * the date alone would let all of those through, and an account with no
     * secret has nothing to verify against.
     */
    public function test_a_confirmation_without_a_secret_is_not_an_enrolment(): void
    {
        $user = User::factory()->create([
            'totp_secret' => null,
            'totp_confirmed_at' => now(),
        ]);

        $this->assertFalse($user->hasConfirmedTotp());
        $this->assertFalse($user->canRegister());

        // And it is sent back to enrolment rather than treated as done.
        $this->actingAs($user)
            ->get(route('totp.setup'))
            ->assertOk();
    }


    /**
     * Guessing is the one thing worth rate-limiting here: six digits is a small
     * space and there is no resend to wait out.
     */
    public function test_repeated_confirmations_are_throttled(): void
    {
        $user = $this->unconfirmedUser();

        $this->actingAs($user)->get(route('totp.setup'));

        $throttled = false;

        for ($attempt = 0; $attempt < 20; $attempt++) {
            if ($this->actingAs($user)
                ->post(route('totp.confirm'), ['code' => '000000'])
                ->status() === 429) {
                $throttled = true;
                break;
            }
        }

        $this->assertTrue($throttled, 'The confirmation endpoint never throttled.');
    }

    // --- Already enrolled -------------------------------------------------

    public function test_an_enrolled_account_is_sent_to_the_done_page(): void
    {
        $user = $this->enrolledUser();

        $this->actingAs($user)
            ->get(route('totp.setup'))
            ->assertRedirect(route('totp.done'));
    }

    public function test_an_enrolled_account_cannot_re_enrol(): void
    {
        $user = $this->enrolledUser();

        $original = (string) $user->totp_secret;

        $this->actingAs($user)
            ->post(route('totp.confirm'), ['code' => $this->currentCodeFor($user)])
            ->assertRedirect(route('totp.done'));

        $this->assertSame($original, (string) $user->fresh()->totp_secret);
    }

    // --- Recovery codes ---------------------------------------------------

    /**
     * The plain codes exist in exactly one response.
     *
     * A reload must not bring them back: afterwards the column holds hashes, and
     * nothing anywhere can recover the originals.
     */
    public function test_recovery_codes_are_shown_once_and_never_again(): void
    {
        $user = $this->unconfirmedUser();

        $this->actingAs($user)->get(route('totp.setup'));
        $this->actingAs($user)->post(route('totp.confirm'), [
            'code' => $this->currentCodeFor($user),
        ]);

        $codes = session('totp_recovery_codes');

        $this->assertIsArray($codes);
        $this->assertCount(8, $codes);

        // The one response that shows them.
        $this->actingAs($user)->get(route('totp.recovery-codes'))->assertOk();

        // And the one after that, which must not contain any of them.
        $later = (string) $this->actingAs($user)->get(route('totp.recovery-codes'))->getContent();

        foreach ($codes as $code) {
            $this->assertStringNotContainsString(
                $code,
                $later,
                'A recovery code reappeared after its one showing.',
            );
        }
    }

    public function test_the_recovery_page_sends_an_unenrolled_account_back_to_setup(): void
    {
        $user = $this->unconfirmedUser();

        $this->actingAs($user)
            ->get(route('totp.recovery-codes'))
            ->assertRedirect(route('totp.setup'));
    }

    // --- Every language ---------------------------------------------------

    public function test_the_setup_page_renders_in_every_language(): void
    {
        $user = $this->unconfirmedUser();

        foreach (['fr', 'en', 'ar'] as $locale) {
            $this->actingAs($user)
                ->get(route('totp.setup', [], $locale))
                ->assertOk()
                ->assertSee('name="code"', escape: false);
        }
    }

    // --- Helpers ----------------------------------------------------------

    private function unconfirmedUser(): User
    {
        $this->seedEdition();

        return User::factory()->unconfirmedTotp()->create();
    }

    private function enrolledUser(): User
    {
        $this->seedEdition();

        return User::factory()->create([
            'totp_secret' => app(Google2FA::class)->generateSecretKey(32),
            'totp_confirmed_at' => now(),
        ]);
    }

    /** The code the visitor's phone would be showing at this instant. */
    private function currentCodeFor(User $user): string
    {
        return app(Google2FA::class)->getCurrentOtp((string) $user->fresh()->totp_secret);
    }

    private function seedEdition(): void
    {
        Edition::factory()->create([
            'year' => 2026,
            'is_current' => true,
            'status' => 'published',
        ]);
    }
}
